// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MultiFileRename
{
    internal sealed partial class Vsix
    {
        public const string Id = "MultiFileRename.c37b5871-4f94-45b5-ab7e-b6234de39dfb";
        public const string Name = "Multi-File Rename";
        public const string Description = @"Rename multiple files in folder";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ashraf Sada";
        public const string Tags = "";
    }
}
